version: 2
jobs:
  checkout_code:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: ~/app
    - save_cache:
          key: gifbot-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/app
  test:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: ~/app
    steps:
      steps:
      - setup_remote_docker
      - restore_cache:
          key: gifbot-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Install pip
          command: apk add --no-cache py-pip=9.0.0-r1
      - run:
          name: Install docker-compose
          command: pip install docker-compose==1.12.0
      - run:
          name: Run tests
          command: docker-compose -f ./docker-compose.test.yml up --exit-code-from gifbot
  

workflows:
  version: 2
  test-and-build-and-deploy:
    jobs:
       - checkout_code
       - test:
          requires:
            - checkout_code
